let _1 = sprites.create(assets.image`hole`, SpriteKind.Projectile)
_1.setPosition(28, 25)
let _2 = sprites.create(assets.image`hole`, SpriteKind.Projectile)
_2.setPosition(74, 25)
let _3 = sprites.create(assets.image`hole`, SpriteKind.Projectile)
_3.setPosition(125, 25)
let _4 = sprites.create(assets.image`hole`, SpriteKind.Projectile)
let _5 = sprites.create(assets.image`hole`, SpriteKind.Projectile)
let _6 = sprites.create(assets.image`hole`, SpriteKind.Projectile)
